-- Chạy trong Supabase Dashboard > SQL Editor

create table if not exists public.orders (
    id bigint generated by default as identity primary key,
    order_code bigint not null unique,
    status text not null default 'PENDING',
    amount integer not null default 0,
    file_path text,
    created_at timestamptz not null default now(),
    expires_at timestamptz,
    paid_at timestamptz,
    download_token text,
    token_expires_at timestamptz
);

create index if not exists orders_status_expires_at_idx
    on public.orders (status, expires_at);

create index if not exists orders_download_token_idx
    on public.orders (download_token);

alter table public.orders enable row level security;

-- App dùng service_role key (SUPABASE_KEY) nên bypass RLS.
-- Nếu dùng anon key, thêm policy phù hợp.
